name: release

on:
  push:
    tags: [ '*.*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: lwch/darwin-crosscompiler:${{ steps.get_version.outputs.VERSION }}
          build-args:
            - "toolchain_version=${{ steps.get_version.outputs.VERSION }}"